source 'https://github.com/ipapamagic/IPaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'IPaCoreDataController_Tests' do
  pod 'IPaCoreDataController', :path => '../'
  
  
end
